name: Build ESP32 examples

on:
  push:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.0

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: esp-idf build
      run: cd examples/thermostat && idf.py build
