name: Build ESP32 examples

on:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v5.0
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: thermostat build
        run: |
          git config --global --add safe.directory .
          . $IDF_PATH/export.sh
          cd examples/thermostat && idf.py build

      - name: simple coap build
        run: |
          git config --global --add safe.directory .
          . $IDF_PATH/export.sh
          cd examples/simple_coap && idf.py build

      - name: tcp tunnel build
        run: |
          git config --global --add safe.directory .
          . $IDF_PATH/export.sh
          cd examples/tcptunnel && idf.py build
