name: Build ESP32 examples

on:
  push:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: esp-idf build
      run: docker run --user="$(id --user):$(id --group)" --rm -t -v "${GITHUB_WORKSPACE}:/app" -w "/app/examples/simple" espressif/idf:release-v5.0 idf.py build
